# Generated by Django 3.1.4 on 2021-02-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_duration',
            field=models.IntegerField(default=0),
        ),
    ]
