# Generated by Django 3.1.4 on 2021-02-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cart_total_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
