# Generated by Django 3.1.3 on 2020-11-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='description',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='practice',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
    ]
