# Generated by Django 3.1.3 on 2020-11-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20201117_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practice',
            options={'verbose_name': 'practice', 'verbose_name_plural': 'practices'},
        ),
        migrations.AlterField(
            model_name='practice',
            name='description',
            field=models.TextField(max_length=1024, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='material',
            field=models.CharField(max_length=1024, verbose_name='Liste de materiel'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='photo1',
            field=models.ImageField(upload_to='', verbose_name='Illustration principale'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='photo2',
            field=models.ImageField(upload_to='', verbose_name='Illustration 2'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='photo3',
            field=models.ImageField(upload_to='', verbose_name='Illustration 3'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='photo4',
            field=models.ImageField(upload_to='', verbose_name='Illustration 4'),
        ),
    ]
