# Generated by Django 3.1.3 on 2020-11-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20201117_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='material',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Liste de materiel'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Illustration principale'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Illustration 2'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Illustration 3'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Illustration 4'),
        ),
    ]
