# Generated by Django 3.1.3 on 2020-11-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_auto_20201117_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='photo4',
        ),
    ]
