# Generated by Django 3.1.3 on 2020-11-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_remove_practice_photo4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='photo1',
            field=models.ImageField(blank=True, default='default_practice.png', null=True,
                                    upload_to='practices_pics', verbose_name='Illustration principale'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='photo2',
            field=models.ImageField(blank=True, default='default_practice.png', null=True,
                                    upload_to='practices_pics', verbose_name='Illustration 2'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='photo3',
            field=models.ImageField(blank=True, default='default_practice.png', null=True,
                                    upload_to='practices_pics', verbose_name='Illustration 3'),
        ),
    ]
