# Generated by Django 3.1.3 on 2020-11-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_auto_20201117_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='practices_pics/',
                                    verbose_name='Illustration principale'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='practices_pics/', verbose_name='Illustration 2'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='practices_pics/', verbose_name='Illustration 3'),
        ),
    ]
