# Generated by Django 3.1.3 on 2020-11-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_auto_20201118_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='photo1',
            field=models.ImageField(blank=True, default='default_practice.png',
                                    upload_to='practices_pics/', verbose_name='Illustration principale'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='photo2',
            field=models.ImageField(blank=True, default='default_practice.png',
                                    upload_to='practices_pics/', verbose_name='Illustration 2'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='photo3',
            field=models.ImageField(blank=True, default='default_practice.png',
                                    upload_to='practices_pics/', verbose_name='Illustration 3'),
        ),
    ]
