# Generated by Django 3.1.3 on 2020-11-23 21:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_auto_20201118_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='photo3',
        ),
        migrations.AlterField(
            model_name='practice',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
