# Generated by Django 3.1.3 on 2020-11-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_auto_20201123_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='photo2',
            field=models.ImageField(blank=True, default='default_practice.png',
                                    upload_to='practices_pics/', verbose_name='Illustration 2'),
        ),
        migrations.AddField(
            model_name='practice',
            name='photo3',
            field=models.ImageField(blank=True, default='default_practice.png',
                                    upload_to='practices_pics/', verbose_name='Illustration 3'),
        ),
        migrations.AddField(
            model_name='practice',
            name='photo4',
            field=models.ImageField(blank=True, default='default_practice.png',
                                    upload_to='practices_pics/', verbose_name='Illustration 4'),
        ),
    ]
