# Generated by Django 3.1.4 on 2021-01-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_auto_20201211_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
