# Generated by Django 3.1.4 on 2021-02-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_auto_20210127_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='duration_in_minutes',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='practice',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
